name: Run Python in Docker

on:
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest
    
    container:
      image: python:3.14-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Python script
        run: python main.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          NAME: ${{ secrets.NAME }}
          RESUME_LINK: ${{ secrets.RESUME_LINK }}
          SUBMIT_URL: ${{ secrets.SUBMIT_URL }}
